Update run-examples.yml

diff --git a/.github/workflows/run-examples.yml b/.github/workflows/run-examples.yml
--- a/.github/workflows/run-examples.yml
+++ b/.github/workflows/run-examples.yml
@@ -2,8 +2,10 @@ name: Run Examples
 
 on: 
   push:
+    # TODO change to [main, develop]
     branches: [ examples ]
   pull_request:
+    # TODO change to [main, develop]
     branches: []
   workflow_dispatch:
 
@@ -30,4 +32,12 @@ jobs:
 
     - name: Find and run Python files in parallel
       run: |
-        find examples -type f -name "*.py" | xargs -P 4 -I {} bash -c 'echo "Running {}"; python "{}"'
+        find examples -type f -name "*.py" | xargs -P 4 -I {} bash -c 'echo "Running {}"; python "{}" 2>> error.log || echo "Failed: {}" >> error.log'
+
+        - name: Check for failed tests
+          run: |
+            if [ -s error.log ]; then
+              echo "Some tests failed. See below for details:"
+              cat error.log
+              exit 1
+            fi
