update version-detector.yml

diff --git a/.github/workflows/version-detector.yml b/.github/workflows/version-detector.yml
--- a/.github/workflows/version-detector.yml
+++ b/.github/workflows/version-detector.yml
@@ -22,16 +22,19 @@ jobs:
         id: version-detector
         run: |
           TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
-          git diff HEAD..origin/"$TARGET_BRANCH" -- eckity/__init__.py | grep -i -n "__version__" > detections.txt
-          if [ -s detections.txt ] && [ "$TARGET_BRANCH" != "main" ]; then
-            cat detections.txt
-            echo "ERROR: The __version__ line should not be changed in pull requests to a branch that is not main."
-            exit 1
-          fi
-          
-          if ! [ -s detections.txt ] && [ "$TARGET_BRANCH" == "main" ]; then
-            cat detections.txt
-            echo "ERROR: The __version__ line was not changed in a pull request to main."
-            exit 1
-          fi
+          git diff HEAD..origin/"$TARGET_BRANCH" --name-only | grep -i -n "eckity/__init.py__" > changed-files.txt
+            if [ -s changed-files.txt ]; then
+              git diff HEAD..origin/"$TARGET_BRANCH" | grep -i -n "__version__" > detections.txt
+              if [ -s detections.txt ] && [ "$TARGET_BRANCH" != "main" ]; then
+                cat detections.txt
+                echo "ERROR: The __version__ line should not be changed in pull requests to a branch that is not main."
+                exit 1
+              fi
+              
+              if ! [ -s detections.txt ] && [ "$TARGET_BRANCH" == "main" ]; then
+                cat detections.txt
+                echo "ERROR: The __version__ line was not changed in a pull request to main."
+                exit 1
+              fi
+            fi
           echo "The __version__ line has been correctly."
